# Generated by Django 4.0 on 2022-03-26 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_confernce_abbrv'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Confernce',
            new_name='Conference',
        ),
    ]
