# Generated by Django 4.0 on 2022-03-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_confernce_conference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kid', models.IntegerField(unique=True, verbose_name="Kaggle's Unique ID")),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
