# Generated by Django 4.0 on 2022-03-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True, verbose_name='Year Season Ended')),
                ('sdate', models.DateField(null=True, verbose_name='Season Start Date')),
            ],
        ),
    ]
