# Generated by Django 4.0 on 2022-03-26 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_teamconference'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(max_length=20)),
                ('rank', models.IntegerField()),
                ('ranking_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.seasonday')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team')),
            ],
        ),
    ]
