# Generated by Django 4.0 on 2022-03-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_game_gameteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('Regular', 'Regular'), ('NCAA', 'NCAA'), ('Secondary', 'Secondary')], default='FAKE', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='gid',
            field=models.CharField(default='FAKE', max_length=50),
            preserve_default=False,
        ),
    ]
