# Generated by Django 4.0 on 2022-03-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_game_game_type_game_gid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('Regular', 'Regular'), ('NCAA', 'NCAA'), ('Secondary', 'Secondary')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='num_ot',
            field=models.IntegerField(null=True),
        ),
    ]
