# Generated by Django 4.0 on 2022-03-26 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_gamestat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.city'),
        ),
    ]
