# Generated by Django 4.0 on 2022-03-26 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_game_city'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gameteam',
            unique_together={('game', 'team')},
        ),
        migrations.CreateModel(
            name='GameTeamStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opp_stat', models.BooleanField(verbose_name='Opponent Stat Flag')),
                ('value', models.FloatField()),
                ('gameteam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.gameteam')),
                ('stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.gamestat')),
            ],
            options={
                'unique_together': {('gameteam', 'stat', 'opp_stat')},
            },
        ),
    ]
