# Generated by Django 4.0 on 2022-03-26 16:32

import django.contrib.postgres.fields.hstore
from django.db import migrations
from django.contrib.postgres.operations import HStoreExtension

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_game_unique_together_and_more'),
    ]

    operations = [
        HStoreExtension(),
        migrations.AddField(
            model_name='gameteam',
            name='features',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=dict),
        ),
    ]
