# Generated by Django 4.0 on 2022-04-14 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_zeropad_num'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ZeroPad',
        ),
    ]
