# Generated by Django 4.0 on 2022-08-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_delete_zeropad'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='hypo',
            field=models.BooleanField(default=False),
        ),
    ]
