# Generated by Django 4.0 on 2022-08-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_game_hypo'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonday',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
