# Generated by Django 4.0 on 2022-09-05 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_seasonday_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourneyseed',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.season'),
        ),
        migrations.AddField(
            model_name='tourneyseed',
            name='seed_code',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tourneyseed',
            name='seed_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tourneyseed',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.team'),
        ),
    ]
