# Generated by Django 4.0 on 2022-09-05 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_tourneyseed_season_tourneyseed_seed_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourneyseed',
            name='seed',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='tourneyseed',
            name='seed_modifier',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
