# Generated by Django 4.0 on 2022-09-05 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_tourneyseed_seed_tourneyseed_seed_modifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourneyseed',
            name='seed_modifier',
        ),
    ]
